export const GET_VETERANS = 'GET_VETERANS';
export const GET_VETERANS_LOADING = 'GET_VETERANS_LOADING';
export const GET_VETERANS_SUCCESS = 'GET_VETERANS_SUCCESS';
export const GET_VETERANS_ERROR = 'GET_VETERANS_ERROR';

export const SET_CURRENT_VETERAN = 'SET_CURRENT_VETERAN';
